# Site settings
title: this.edgeofforever.net
description: > # this means to ignore newlines until "baseurl:"
  reaching through the internet to opine about transhumanist art in new york city and beyond; an exploration of life, love, and lectons surfing a wave of future-shock. #emergence #weatherpunk #post_human
baseurl: "" # the subpath of your site, e.g. /blog/
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://localhost:4000
disqus_shortname: 
reading_time:     true
words_per_minute: 200


# Owner/author information
owner:
  name:           RB
  avatar:         rb_moss.png
  bio:            "a creative technologist and digital renaissance human with a background that spans areas from cosmology to microbiology. "
  email:          this@edgeofforever.net
  # Social networking links used in footer. Update and remove as you like.
  twitter:        roastbeest
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      roastbeest
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics: UA-34380433-2   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter:  rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of posts to show on home page
paginate: 3

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]